#!/bin/bash
#
# Based on rxOC v_stopgap by fullzero
#
# RXOS v0.1 by dazarn
#
# USE ALL CAPS
#
# ZEC  NICE  HUSH  ZEN  ZCL  MUSIC  ETC  EXP  ETH  DCR  PASC
# DUAL_ETC_DCR    DUAL_ETC_PASC    DUAL_ETC_LBC    DUAL_ETC_SC
# DUAL_EXP_DCR    DUAL_EXP_PASC    DUAL_EXP_LBC    DUAL_EXP_SC
# DUAL_ETH_DCR    DUAL_ETH_PASC    DUAL_ETH_LBC    DUAL_ETH_SC
# DUAL_MUSIC_DCR  DUAL_MUSIC_PASC  DUAL_MUSIC_LBC  DUAL_MUSIC_SC

COIN="ETH"

TEAMVIEWER="NO"                 # YES NO

SSH="YES"                       # YES NO

PERFORMANCE_LEVEL="HIGH"        # HIGH LOW

# select level: to see supported clocks scroll to the top of the mining process
__CORE_OVERCLOCK_LEVEL=3   # for ETH use lowest without decreasing the hashrate / Highest for ZEC
MEMORY_OVERCLOCK_LEVEL=2   # use highest level

OVERDRIVE="YES"                  # YES NO

# unlikely to be stable above 10%
OVERDRIVE_PERCENT=10     # for zec 5 for eth 10

USE_ENVIRONMENTAL_VARIBLES="NO"

MANUAL_FAN="YES"             	# YES NO

# Set fan speed if MANUAL_FAN="YES"
# set fanspeed to between 150 and 255
# DO NOT SET BELOW 150, I HIGHLY RECOMMEND 175 or higher
FAN_SPEED=255

# If you are using a slow USB Key
SLOW_USB_KEY_MODE="NO"        	# YES NO

# Mine XMR with CPU
plusCPU="NO"		        # YES NO

# Number of threads for plusCPU
threadCOUNT="1"                 	# varies per CPU

# worker name implementation
IP_AS_WORKER="mrig13"
echo workername: $IP_AS_WORKER

########################################################################################

# set YOUR ADDRESSES, WORKERS, POOL and PORT:

OPTIMINERorCLAYMORE="CLAYMORE"  # choose OPTIMINER  or  CLAYMORE

ZEC_WORKER="$IP_AS_WORKER"
ZEC_ADDRESS=""
ZEC_POOL=""
ZEC_INTENSITY=6
ZEC_EXTENTION_ARGUMENTS=" -allpools 1"

ZCL_WORKER="$IP_AS_WORKER"
ZCL_ADDRESS=""
ZCL_POOL=""
ZCL_INTENSITY=6
ZCL_EXTENTION_ARGUMENTS=""

ZEN_WORKER="$IP_AS_WORKER"
ZEN_ADDRESS=""
ZEN_POOL=""
ZEN_INTENSITY=6
ZEN_EXTENTION_ARGUMENTS=""

HUSH_WORKER="$IP_AS_WORKER"
HUSH_ADDRESS=""
HUSH_POOL=""
HUSH_INTENSITY=6
HUSH_EXTENTION_ARGUMENTS=""

BTC_ADDRESS=""

# NICE autoconverts to BTC: ensure you update BTC_ADDRESS if you use NICE
NICE_WORKER="$IP_AS_WORKER"
NICE_POOL="stratum+tcp://daggerhashimoto.eu.nicehash.com:3353"
GENOIL_NICE_POOL="daggerhashimoto.eu.nicehash.com:3353"
NICE_EXTENTION_ARGUMENTS=""   # add any additional claymore arguments desired here

ETHERMINEdotORG="YES"

CLAYMORE_VERSION="10_1"    # choose 10_1 or 9_5  or  9_4  or  8_0

GENOILorCLAYMORE="CLAYMORE"  # choose GENOIL  or  CLAYMORE

ETH_WORKER="$IP_AS_WORKER"
ETH_ADDRESS="0x57b42099bcf13b0ad1bd7c402e85d2e1ebb03e6e"
ETH_POOL="eu1.ethermine.org:4444"
ETH_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

ETC_WORKER="$IP_AS_WORKER"
ETC_ADDRESS=""
ETC_POOL="us1-etc.ethermine.org:4444"
ETC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

EXP_WORKER="$IP_AS_WORKER"
EXP_ADDRESS=""
EXP_POOL="exp-us.dwarfpool.com:8018"
EXP_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

MUSIC_WORKER="$IP_AS_WORKER"
MUSIC_ADDRESS=""
MUSIC_POOL="stratum+tcp://213.154.202.174:3334"
MUSIC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

SC_WORKER="$IP_AS_WORKER"
SC_ADDRESS=""
SC_POOL="sia-us-east1.nanopool.org:7777"
SC_GW_POOL="sia-us-east1.nanopool.org:9980"

DCR_WORKER="$IP_AS_WORKER"
DCR_ADDRESS=""
DCR_POOL="stratum+tcp://dcr.suprnova.cc:3252"

PASC_WORKER="$IP_AS_WORKER"
PASC_ADDRESS=""
PASC_POOL="pasc-us-east1.nanopool.org:15555"

# if plusCPU is "YES" replace with your XMR info
XMR_WORKER="$IP_AS_WORKER"
XMR_ADDRESS=""
XMR_POOL="stratum+tcp://xmr-us-east1.nanopool.org:14444"

#  settings above: ALL ADJUSTABLE SETINGS ABOVE THIS LINE
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#########################################################################
#  implementation below: NO SETTINGS BELOW

IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')

echo ''
echo rig IP: $IP
echo ''

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $USE_ENVIRONMENTAL_VARIBLES == "YES" ]
then
export GPU_FORCE_64BIT_PTR=1
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100
echo ENVIRONMENTAL VARIBLES SET
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

echo ''
lspci | grep VGA

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

sudo '/home/m1/rocm-smi' -s
echo ''

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

sudo '/home/m1/rocm-smi' -r

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $PERFORMANCE_LEVEL == "HIGH" ]
then
sudo '/home/m1/rocm-smi' --setperflevel high
fi

if [ $PERFORMANCE_LEVEL == "LOW" ]
then
sudo '/home/m1/rocm-smi' --setperflevel low
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $OVERDRIVE == "YES" ]
then
sudo '/home/m1/rocm-smi' --setoverdrive $OVERDRIVE_PERCENT
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

sudo '/home/m1/rocm-smi' --setmclk $MEMORY_OVERCLOCK_LEVEL

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

sudo '/home/m1/rocm-smi' --setsclk $__CORE_OVERCLOCK_LEVEL

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $TEAMVIEWER == "YES" ]
then
sudo teamviewer --daemon enable
if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi
fi

if [ $TEAMVIEWER == "NO" ]
then
sudo teamviewer --daemon disable
if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi
fi

if [ $SSH == "YES" ]
then
sudo cp '/etc/init/ssh.conf-on' '/etc/init/ssh.conf'
if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi
fi

if [ $SSH == "NO" ]
then
sudo cp '/etc/init/ssh.conf-off' '/etc/init/ssh.conf'
if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi
fi

if [ $plusCPU == "YES" ]
then
HCD='/home/m1/cpuOPT/cpuminer'
XMRADDR="$XMR_ADDRESS.$XMR_WORKER"
guake -r $HCD -e "$HCD -a cryptonight -o $XMR_POOL -u $XMRADDR -p x -t $threadCOUNT"
fi

ROC='/home/m1/rocm-smi'

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $MANUAL_FAN == "YES" ]
then
sudo '/home/m1/rocm-smi' --setfan $FAN_SPEED -f
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ "$FAN_SPEED" -lt "105" ]
then
    FAN_SPEED=105
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $MANUAL_FAN == "NO" ]
then
echo "FANS ON AUTO"
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $SLOW_USB_KEY_MODE == "YES" ]
then
sleep 6
fi

if [ $COIN == "NICE" ]
then

if [ $GENOILorCLAYMORE == "GENOIL" ]
then
HCD='/home/m1/eth/Genoil/ethminer'

NICEADDR="$BTC_ADDRESS.$NICE_WORKER"
until $HCD -SP 2 -S $GENOIL_NICE_POOL -O $NICEADDR:x -G
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $GENOILorCLAYMORE == "CLAYMORE" ]
then
if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

NICEADDR="$BTC_ADDRESS.$NICE_WORKER"

until $HCD -epool $NICE_POOL -ewal $NICEADDR -epsw x -esm 3 -allpools 1 -estale 0 -dbg -1 $NICE_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
fi

if [ $COIN == "ZEC" ]
then

if [ $OPTIMINERorCLAYMORE == "OPTIMINER" ]
then
cd /home/m1/zec/optiminer-zcash
export GPU_FORCE_64BIT_PTR=1
ZECADDR="$ZEC_ADDRESS.$ZEC_WORKER"
HCD='/home/m1/zec/optiminer-zcash/optiminer-zcash'

screen -dmS miner $HCD -s $ZEC_POOL -u $ZECADDR -p x -i $ZEC_INTENSITY

echo "mining in screen: screen -r miner"

while [ 1 ]
do
sleep 100
done
fi

if [ $OPTIMINERorCLAYMORE == "CLAYMORE" ]
then
HCD='/home/m1/zec/c12_5/zecminer64'

ZECADDR="$ZEC_ADDRESS.$ZEC_WORKER"
screen -dmS miner $HCD -zpool $ZEC_POOL -zwal $ZECADDR -zpsw x -dbg -1 -i $ZEC_INTENSITY $ZEC_EXTENTION_ARGUMENTS

echo "mining in screen: screen -r miner"

while [ 1 ]
do
sleep 100
done
fi
fi


if [ $COIN == "ZCL" ]
then

if [ $OPTIMINERorCLAYMORE == "OPTIMINER" ]
then
cd /home/m1/zec/optiminer-zcash
export GPU_FORCE_64BIT_PTR=1
ZCLADDR="$ZCL_ADDRESS.$ZCL_WORKER"
HCD='/home/m1/zec/optiminer-zcash/optiminer-zcash'

until $HCD -s $ZCL_POOL -u $ZCLADDR -p x -i $ZCL_INTENSITY
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $OPTIMINERorCLAYMORE == "CLAYMORE" ]
then
HCD='/home/m1/zec/c12_5/zecminer64'

ZCLADDR="$ZCL_ADDRESS.$ZCL_WORKER"
until $HCD -zpool $ZCL_POOL -zwal $ZCLADDR -zpsw x -dbg -1 -i $ZCL_INTENSITY $ZCL_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
fi

if [ $COIN == "ZEN" ]
then

if [ $OPTIMINERorCLAYMORE == "OPTIMINER" ]
then
cd /home/m1/zec/optiminer-zcash
export GPU_FORCE_64BIT_PTR=1
ZENADDR="$ZEN_ADDRESS.$ZEN_WORKER"
HCD='/home/m1/zec/optiminer-zcash/optiminer-zcash'

until $HCD -s $ZEN_POOL -u $ZENADDR -p x -i $ZEN_INTENSITY
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $OPTIMINERorCLAYMORE == "CLAYMORE" ]
then
HCD='/home/m1/zec/c12_5/zecminer64'

ZENADDR="$ZEN_ADDRESS.$ZEN_WORKER"
until $HCD -zpool $ZEN_POOL -zwal $ZENADDR -zpsw x -dbg -1 -i $ZEN_INTENSITY $ZEN_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
fi

if [ $COIN == "HUSH" ]
then

if [ $OPTIMINERorCLAYMORE == "OPTIMINER" ]
then
cd /home/m1/zec/optiminer-zcash
export GPU_FORCE_64BIT_PTR=1
HUSHADDR="$HUSH_ADDRESS.$HUSH_WORKER"
HCD='/home/m1/zec/optiminer-zcash/optiminer-zcash'

until $HCD -s $HUSH_POOL -u $HUSHADDR -p x -i $HUSH_INTENSITY
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $OPTIMINERorCLAYMORE == "CLAYMORE" ]
then
HCD='/home/m1/zec/c12_5/zecminer64'

HUSHADDR="$HUSH_ADDRESS.$HUSH_WORKER"
until $HCD -zpool $HUSH_POOL -zwal $HUSHADDR -zpsw x -dbg -1 -i $HUSH_INTENSITY $HUSH_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
fi

if [ $COIN == "ETC" ]
then

if [ $GENOILorCLAYMORE == "CLAYMORE" ]
then
if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "10_1" ]
then
HCD='/home/m1/eth/10_1/ethdcrminer64'
fi
fi

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

screen -dmS miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -mode 1 -dbg -1 $ETC_EXTENTION_ARGUMENTS

echo "mining in screen: screen -r miner"

while [ 1 ]
do
sleep 100
done
fi

if [ $COIN == "EXP" ]
then

if [ $GENOILorCLAYMORE == "GENOIL-CURRENTLY-NOT-SUPPORTED" ]
then
HCD='/home/m1/eth/Genoil/ethminer'

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
until $HCD -S $EXP_POOL -O $EXPADDR:x -G
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

#if [ $GENOILorCLAYMORE == "CLAYMORE" ]
#then
if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "10_1" ]
then
HCD='/home/m1/eth/10_1/ethdcrminer64'
fi


EXPADDR="$EXP_ADDRESS/$EXP_WORKER"

until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -mode 1 -allpools 1 -dbg -1 $EXP_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
#fi

if [ $COIN == "ETH" ]
then

if [ $GENOILorCLAYMORE == "CLAYMORE" ]
then
if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "10_1" ]
then
HCD='/home/m1/eth/10_1/ethdcrminer64'
fi
fi

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

screen -dmS miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -mode 1 -dbg -1 $ETH_EXTENTION_ARGUMENTS

echo "mining in screen: screen -r miner"

while [ 1 ]
do
sleep 100
done
fi

if [ $COIN == "MUSIC" ]
then

if [ $GENOILorCLAYMORE == "GENOIL-CURRENTLY-NOT-SUPPORTED" ]
then
HCD='/home/m1/eth/Genoil/ethminer'

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
until $HCD -S $MUSIC_POOL -O $MUSICADDR:x -G
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

#if [ $GENOILorCLAYMORE == "CLAYMORE" ]
#then
if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -mode 1 -allpools 1 -dbg -1 $MUSIC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
#fi

if [ $COIN == "DCR" ]
then
HCD='/home/m1/pasc/sgminer'
ADDR="$DCR_ADDRESS.$DCR_WORKER"
until $HCD -k decred -o $DCR_POOL -u $ADDR -p x -p x -I 21 -w 64 -g2
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "PASC" ]
then
HCD='/home/m1/pasc/sgminer'
ADDR="$PASC_ADDRESS..$PASC_WORKER"

until $HCD -k pascal -o $PASC_POOL -u $ADDR -p x -p x -I 21 -w 64 -g2
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETC_DCR" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"
until $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dbg -1 $ETC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETC_PASC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"
until $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -dbg -1 $ETC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETC_LBC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"
until $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -dbg -1 $ETC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETC_SC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"
until $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -allpools 1 -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -dcri 70 -dbg -1 $ETC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_EXP_DCR" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
DADDR="$DCR_ADDRESS.$DCR_WORKER"
until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -allpools 1 -dpool $DCR_POOL -dwal $DADDR -dpsw x $EXP_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_EXP_PASC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
ADDR="$PASC_ADDRESS..$PASC_WORKER"
until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -allpools 1 -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -dbg -1 $EXP_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_EXP_LBC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
ADDR="$LBC_ADDRESS.$LBC_WORKER"
until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -allpools 1 -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -dbg -1 $EXP_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_EXP_SC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
SCADDR="$SC_ADDRESS/$SC_WORKER"
until $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -allpools 1 -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -dcri 70 -dbg -1 $EXP_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_MUSIC_DCR" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
DADDR="$DCR_ADDRESS.$DCR_WORKER"
until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -allpools 1 -dpool $DCR_POOL -dwal $DADDR -dpsw x -dbg -1 $MUSIC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_MUSIC_PASC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
ADDR="$PASC_ADDRESS..$PASC_WORKER"
until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -allpools 1 -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -dbg -1 $MUSIC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_MUSIC_LBC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
ADDR="$LBC_ADDRESS.$LBC_WORKER"
until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -allpools 1 -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -dbg -1 $MUSIC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_MUSIC_SC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
SCADDR="$SC_ADDRESS/$SC_WORKER"
until $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -allpools 1 -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -dcri 70 -dbg -1 $MUSIC_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETH_DCR" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"
until $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dbg -1 $ETH_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETH_PASC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"
until $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -dbg -1 $ETH_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETH_LBC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"
until $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -dbg -1 $ETH_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi

if [ $COIN == "DUAL_ETH_SC" ]
then

if [ $CLAYMORE_VERSION == "9_5" ]
then
HCD='/home/m1/eth/9_5/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "9_4" ]
then
HCD='/home/m1/eth/9_4/ethdcrminer64'
fi

if [ $CLAYMORE_VERSION == "8_0" ]
then
HCD='/home/m1/eth/8_0/ethdcrminer64'
fi

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $ETHERMINEdotORG == "YES" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"
until $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -allpools 1 -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -dcri 70 -dbg -1 $ETH_EXTENTION_ARGUMENTS
   do
   echo "FAILURE; reinit in 5" >&2
   sleep 5
done
fi
