#!/bin/bash
#
# Based on rxOC v_stopgap by fullzero & nvOC v0019-2.0 - Community Release by papampi, Stubo and leenoox
#
# RXOS v0.1 by dazarn
#
# USE ALL CAPS
#
# ZEC  NICE  HUSH  ZEN  ZCL  MUSIC  ETC  EXP  ETH  DCR  PASC
# DUAL_ETC_DCR    DUAL_ETC_PASC    DUAL_ETC_LBC    DUAL_ETC_SC
# DUAL_EXP_DCR    DUAL_EXP_PASC    DUAL_EXP_LBC    DUAL_EXP_SC
# DUAL_ETH_DCR    DUAL_ETH_PASC    DUAL_ETH_LBC    DUAL_ETH_SC
# DUAL_MUSIC_DCR  DUAL_MUSIC_PASC  DUAL_MUSIC_LBC  DUAL_MUSIC_SC
#

COIN="ETH"

AUTO_START_MINER="YES"      # YES or NO # Set this to NO when troubleshooting, this will prevent the watchdog restarting the rig

NUMBER_GPUS_INSTALLED=""    # Number or "" # Set number of GPUs installed. Watchdog will check installed vs detected. Leave empty to not check

TEAMVIEWER="NO"                 # YES NO

SSH="YES"                       # YES NO

AUTO_REBOOT="NO"            # YES or NO # If you want this rig to periodically reboot set this to YES

REBOOT_TIMEOUT_IN_MINUTES=2880  # If AUTO_REBOOT is set to YES, use this to set how often to reboot, 1440 = 24 hours, 2880 = 48 hours

MINER_WATCHDOG="YES"        # YES or NO # Monitors the rig and automatically corrects the detected problems. Highly recommended to use this!

PERFORMANCE_LEVEL="HIGH"        # HIGH LOW

# select level: to see supported clocks scroll to the top of the mining process
__CORE_OVERCLOCK_LEVEL=3   # for ETH use lowest without decreasing the hashrate / Highest for ZEC
MEMORY_OVERCLOCK_LEVEL=2   # use highest level

OVERDRIVE="YES"                  # YES NO

# unlikely to be stable above 10%
OVERDRIVE_PERCENT=10     # for zec 5 for eth 10

USE_ENVIRONMENTAL_VARIBLES="NO"

MANUAL_FAN="YES"             	# YES NO

# Set fan speed if MANUAL_FAN="YES"
# set fanspeed to between 150 and 255
# DO NOT SET BELOW 150, I HIGHLY RECOMMEND 175 or higher
FAN_SPEED=255

# If you are using a slow USB Key
SLOW_USB_KEY_MODE="NO"        	# YES NO

# Mine XMR with CPU
plusCPU="NO"		        # YES NO

# Number of threads for plusCPU
threadCOUNT="1"                 	# varies per CPU

# worker name implementation
WORKER_NAME="mrig13"
echo workername: $WORKER_NAME

########################################################################################

########################################################
#                                                      #
# Addresses, pools, ports, intensity, miner settings   #
#                                                      #
########################################################

# For zpool use MINER_PWD="$WORKERNAME,c=btc"
MINER_PWD="x"               # Set the miner password. Default: x


OPTIMINERorCLAYMORE="CLAYMORE"  # choose OPTIMINER  or  CLAYMORE

ZEC_WORKER="$WORKER_NAME"
ZEC_ADDRESS=""
ZEC_POOL=""
ZEC_INTENSITY=6
ZEC_EXTENTION_ARGUMENTS=" -allpools 1"

ZCL_WORKER="$WORKER_NAME"
ZCL_ADDRESS=""
ZCL_POOL=""
ZCL_INTENSITY=6
ZCL_EXTENTION_ARGUMENTS=""

ZEN_WORKER="$WORKER_NAME"
ZEN_ADDRESS=""
ZEN_POOL=""
ZEN_INTENSITY=6
ZEN_EXTENTION_ARGUMENTS=""

HUSH_WORKER="$WORKER_NAME"
HUSH_ADDRESS=""
HUSH_POOL=""
HUSH_INTENSITY=6
HUSH_EXTENTION_ARGUMENTS=""

BTC_ADDRESS=""

# NICE autoconverts to BTC: ensure you update BTC_ADDRESS if you use NICE
NICE_WORKER="$WORKER_NAME"
NICE_POOL="stratum+tcp://daggerhashimoto.eu.nicehash.com:3353"
GENOIL_NICE_POOL="daggerhashimoto.eu.nicehash.com:3353"
NICE_EXTENTION_ARGUMENTS=""   # add any additional claymore arguments desired here

ETHERMINEdotORG="YES"

CLAYMORE_VERSION="10_1"    # choose 10_1 or 9_5  or  9_4  or  8_0

GENOILorCLAYMORE="CLAYMORE"  # choose GENOIL  or  CLAYMORE

ETH_WORKER="$WORKER_NAME"
ETH_ADDRESS="0x57b42099bcf13b0ad1bd7c402e85d2e1ebb03e6e"
ETH_POOL="eu1.ethermine.org:4444"
ETH_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

ETC_WORKER="$WORKER_NAME"
ETC_ADDRESS=""
ETC_POOL="us1-etc.ethermine.org:4444"
ETC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

EXP_WORKER="$WORKER_NAME"
EXP_ADDRESS=""
EXP_POOL="exp-us.dwarfpool.com:8018"
EXP_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

MUSIC_WORKER="$WORKER_NAME"
MUSIC_ADDRESS=""
MUSIC_POOL="stratum+tcp://213.154.202.174:3334"
MUSIC_EXTENTION_ARGUMENTS=""    # add any additional claymore arguments desired here

SC_WORKER="$WORKER_NAME"
SC_ADDRESS=""
SC_POOL="sia-us-east1.nanopool.org:7777"
SC_GW_POOL="sia-us-east1.nanopool.org:9980"

DCR_WORKER="$WORKER_NAME"
DCR_ADDRESS=""
DCR_POOL="stratum+tcp://dcr.suprnova.cc:3252"

PASC_WORKER="$WORKER_NAME"
PASC_ADDRESS=""
PASC_POOL="pasc-us-east1.nanopool.org:15555"

# if plusCPU is "YES" replace with your XMR info
XMR_WORKER="$WORKER_NAME"
XMR_ADDRESS=""
XMR_POOL="stratum+tcp://xmr-us-east1.nanopool.org:14444"


#########################################################################
