#!/bin/bash
#

source ~/1bash

TIMEIN=$REBOOT_TIMEOUT_IN_MINUTES

TIMEOUT=$(($TIMEIN * 60))

sleep 2

echo ""
echo "Reboot in $TIMEOUT seconds"

sleep $TIMEOUT
pkill -e gnome-terminal
pkill -f 3main
pkill -e screen
echo ""
echo "reboot in 10 seconds"
sleep 10
sudo reboot
