#!/bin/bash
#
# Based on rxOC v_stopgap by fullzero & nvOC v0019-2.0 - Community Release by papampi, Stubo and leenoox
#
# RXOS v0.1 by dazarn
#
# USE ALL CAPS
#

source /home/m1/1bash

TIMEIN=$REBOOT_TIMEOUT_IN_MINUTES

TIMEOUT=$(($TIMEIN * 60))

sleep 2

echo ""
echo "Reboot in $TIMEOUT seconds"

sleep $TIMEOUT
pkill -e gnome-terminal
pkill -f 3main
pkill -e screen
echo ""
echo "reboot in 10 seconds"
sleep 10
sudo reboot
